### ISSUE TITLE
Section 2.2: Multiple permissions per type; add $ notation to every element?

### ISSUE THREAD

**Issue by danielfett** [oauthstuff/draft-oauth-rar#1]
It might be more consistent to add the instance name to every element in the data structure; otherwise, the instance name of the first element in this example is undefined:

```JSON
{  
   "https://scheme.example.org/imap":{  
      "server":"imap.example.com",
      "mailbox":"/users/<current>",
      "access":[  
         "read",
         "write"
      ]
   },
   "https://scheme.example.org/imap$2":{  
      "server":"imap.example.org",
      "mailbox":"/users/shared/folder3",
      "access":[  
         "read"
      ]
   }
}
```
Proposal:

```JSON
{  
   "https://scheme.example.org/imap$0":{  
      "server":"imap.example.com",
      "mailbox":"/users/<current>",
      "access":[  
         "read",
         "write"
      ]
   },
   "https://scheme.example.org/imap$1":{  
      "server":"imap.example.org",
      "mailbox":"/users/shared/folder3",
      "access":[  
         "read"
      ]
   }
}
```

**Comment by panva** [comment]
I’m not a fan of this $ notation. Why can’t the value just be an array?

**Comment by tlodderstedt** [comment]
you mean the "authorization_details" object contains an array?

**Comment by panva** [comment]
@tlodderstedt no,

i mean solving "Multiple instances of the same authorization data type" like this instead of appeding `$index`

```json
{
  "https://scheme.example.org/imap": [
    {"server":"imap.example.com","mailbox":"/users/<current>","access":["read","write"]},
    {"server":"imap.example.org","mailbox":"/users/shared/folder3","access":["read"]}
  ]
  }
```

**Comment by tlodderstedt** [comment]
How would you handle the situation where the client just wants a single authorization data value?

{
  
"https://scheme.example.org/imap"
: [
    {
"server":"imap.example.com","mailbox":"/users/<current>","access":["read","write"]}
  ]
  }

or 

{
  
"https://scheme.example.org/imap"{
"server":"imap.example.com","mailbox":"/users/<current>","access":["read","write”]
}

**Comment by panva** [comment]
the latter

**Comment by tlodderstedt** [comment]
So "https://scheme.example.org/imap" sometimes would be an object and sometimes it would be am array. I personally don't like this kind of "element type morphing".

**Comment by panva** [comment]
I agree but why invent a new syntax for something JSON has built in.

**Comment by panva** [comment]
Furthermore you schema (the key) may have a definition whether array is or isn’t defined.

**Comment by tlodderstedt** [comment]
> I agree but why invent a new syntax for something JSON has built in.

you mean developers are used to it?

> Furthermore the schema may have a definition whether array is or isn’t permitted or even required.

What do you mean? A JSON scheme?

**Comment by panva** [comment]
> you mean developers are used to it?

I mean I as a developer will take the object and `reduce` it to an array anyway - why do I have to do that when JSON has a perfectly suitable type for lists :)

I also won't have to go through the trouble of tracking the indexes and figuring out if they're missing, possibly input validation that there is always a 0 element and every index in between 0 and `n`...

**Comment by b---c** [comment]
I'm with @panva here - inventing some special notation to express a list when JSON already has a perfectly suitable way to do it seems like a pretty suspect approach.

**Comment by jricher** [comment]
I'd already proposed to @tlodderstedt to use an array for the core structure, and I've prepared a pull request for it #5

**Comment by tlodderstedt** [comment]
I just merged the PR including the new structure, which also resolves this issue.
