### ISSUE TITLE
Clarification needed on combining with resource indicators

### ISSUE THREAD

**Issue by danielfett** [oauthstuff/draft-oauth-rar#24]
I think that Section 2.5, describing the relationship to the resource parameter, needs a sentence to clarify how authorization_details work together with the resource parameter.

The text currently says: 

    The "locations" and the "identifier" elements together allow the AS
    to determine the resource a client wants to access as shown in
    following example:

What is missing here is the role of location and identifier. I assume that the location can be associated by the AS with an RS, while the identifier becomes part of the URL to request something from the RS? 

The example is incomplete: it should say what happens at the AS and RS when these authorization_details are used. It should also show a token request.

**Comment by tlodderstedt** [comment]
added extensive description in the latest PR (audience and co)
