### ISSUE TITLE
Section 7: Privacy Considerations; Encryption might not be enough

### ISSUE THREAD

**Issue by danielfett** [oauthstuff/draft-oauth-rar#3]
Encrypting the authorization_details might not be enough to ensure confidentiality. An attacker that has eavesdropped on an encrypted authorization_details object might use that same object in new a request to the same AS. The AS will then decrypt the authorization_details object and _potentially_ present the details to the user, here: the attacker.

**Comment by tlodderstedt** [comment]
as discussed, I don't see a generic solution to this problem. I added a statement describing the general problem and obliging the AS to consider it.
