### ISSUE TITLE
Refactor Section 2.1

### ISSUE THREAD

**Issue by tlodderstedt** [oauthstuff/draft-oauth-rar#33]
- split text about "type" and default elements
- move text re namespaces to "type"

**Comment by jricher** [comment]
Motivation: the `type` element acts as a functionality switch that determines what other fields and details are allowed in the section, whereas all the other elements determine what the actual request is for. Most of the namespacing issues are going to be around the `type` element itself, though the registry for the "common" elements will probably want to follow similar advice.

**Comment by jricher** [comment]
See also #28 for important discussion about comparison and processing of the `type` field.
