### ISSUE TITLE
aud in JWT Access Token and Token Introspection Response

### ISSUE THREAD

**Issue by TakahikoKawasaki** [oauthstuff/draft-oauth-rar#39]
draft-lodderstedt-oauth-rar-04 has an example of JWT Access Token (3.4.1. Token Content) and an example of Token Introspection Response (3.6. Token Introspection Response). Both include `aud`.

I expected that the value of `aud` is a list of (merged?) `locations` or `resource`s. However, The values of `aud` in the examples are `a7AfcPcsl2` and `s6BhdRkqt3`. Are the values in the examples correct?

FYI: "Resource Indicators for OAuth 2.0" ([draft-08](https://tools.ietf.org/html/draft-ietf-oauth-resource-indicators-08)) says as follows:

> The authorization server SHOULD audience-restrict issued access tokens to the resource(s) indicated by the "resource" parameter. Audience restrictions can be communicated in JSON Web Tokens [RFC7519] with the "aud" claim and the top-level member of the same name provides the audience restriction information in a Token Introspection [RFC7662] response.  The authorization server may use the exact "resource" value as the audience or it may map from that value to a more general URI or abstract identifier for the given resource.

**Comment by b---c** [comment]
Yeah, Taka has a point here. Those do not seem correct.

**Comment by tlodderstedt** [comment]
seems we need to decide whether/how locations are going into the aud field :-)

I see to solutions: 

1. the RS has an internal ID and the locations elements are mapped to those IDs -> authz details element needs to be modified
2. the RS is identified by the location -> the aud needs to contain the location

I'm leaning towards (1) since this would allow to map multiple locations to internal ID AND the internal ID would survive a URL change of the RS.

**Comment by TakahikoKawasaki** [comment]
Another way of thinking is _"because `locations` are already included in `authorization_details`, they don't have be added to `aud` duplicately."_

`locations` exists in each element in the `authorization_details` array independently of each other. Merging `locations`' into one `aud` would discard the separation. I'm not sure what value can be provided by the flattened locations in one place.

It might be wise not to touch `aud`.

**Comment by jricher** [comment]
I'm with Taka here -- the `locations` field is the resource server _as known by the client_, wheras the `aud` field is the resource server _as known by the resource server itself_. Sometimes, perhaps often, they're the same. Sometimes they aren't. But how they map is an internal detail to the AS. The best we can do is communicate a potential pattern, like the resource indicator draft. "You can put the `location` into the `aud` field if you want to do that."

**Comment by tlodderstedt** [comment]
@jricher Didn’t I state the same?

**Comment by jricher** [comment]
@tlodderstedt What I'm saying is basically your (1) but not as a prescriptive requirement, instead as a suggested recipe.

**Comment by tlodderstedt** [comment]
wfm
