### ISSUE TITLE
Mention that JSON schema validation can be useful with the authorization_details

### ISSUE THREAD

**Issue by vdzhuvinov** [oauthstuff/draft-oauth-rar#44]
Given the potential complexity of the authorization_details objects we were thinking of enabling applications to configure a JSON schema for a "type", so the overall correctness of the request parameter can be checked and return an `invalid_request` error on the schema check failing, before passing the details to the consent logic.

One fairly popular JSON schema is https://json-schema.org . The authors are working on making it a standard: https://json-schema.org/specification.html

Here is the main spec: https://tools.ietf.org/html/draft-handrews-json-schema-02

As a side note, I was pleasantly surprised that the schema also allows for specifying the JSON content in a JWT, for example

```
{
    "type": "string",
    "contentMediaType": "application/jwt",
    "contentSchema": {
        "type": "array",
        "minItems": 2,
        "items": [
            {
                "const": {
                    "typ": "JWT",
                    "alg": "HS256"
                }
            },
            {
                "type": "object",
                "required": ["iss", "exp"],
                "properties": {
                    "iss": {"type": "string"},
                    "exp": {"type": "integer"}
                }
            }
        ]
    }
}
```

**Comment by tlodderstedt** [comment]
I like the idea and had mentioned this before in conversations about RAR. We use JSON schema in OpenID Connect for Identity Assurance and it helps to omit the obvious errors. However, JSON schema has limitations when it comes to polymorphism.

I therefore think we could mention JSON schema (or scheme validation in general). I could also imagine to have a mechanism for the entity maintaining the authorization data type to specify the scheme using JSON schema. I don’t think this would be the client, I more see this as a RS/API definition thing.

Thoughts?

**Comment by b---c** [comment]
A mention and maybe even example(s) seem okay but I would not want to see a requirement or dependency on JSON schema.

**Comment by jricher** [comment]
I'm strongly against requiring JSON Schema for implementation, same with JSONLD or other structured JSON systems. 

Nothing is stopping someone from defining their own "type" structure using one of those schema systems, though. An example in an appendix would be fine with me, but I don't think any normative language is a good idea.

**Comment by tlodderstedt** [comment]
added notes to implementation considerations in PR #71
