### ISSUE TITLE
Enriching/transforming authorization_details in token response

### ISSUE THREAD

**Issue by tlodderstedt** [oauthstuff/draft-oauth-rar#47]
we have identified use cases, where it could be useful to enrich the authorization_details object as passed on the authorization in the token response. 

Example: the client asks for access to balance and transactions on the user's bank accounts, but leaves the decision of what accounts access is given too to the user. 

{
  "type": "account_information",
  "access": {
    "accounts": [],
    "balances": [],
    "transactions": []
  },
  "recurringIndicator":true
}

The user, in the authorization flow, picks a sub set of her accounts with the bank and authorizes the client for accessing balance and transactions. The client in the end needs to know what accounts it is allowed to access. We identified two ways to convey that information: 1) the account information API has a special resource listing the account objects authorized under a certain access token. 2) the token response adds the information about the accounts (and features with the respective account) to the authorization details object. Here is an example:

{
    "access_token": "2YotnFZFEjr1zCsicMWpAA",
    "token_type": "example",
    "expires_in": 3600,
    "refresh_token": "tGzv3JokF0XG5Qx2TlKWIA",
    "authorization_details": [
        {
            "type": "account_information",
            "access": {
                "accounts": [
                    {
                        "iban": "DE2310010010123456789"
                    },
                    {
                        "maskedPan": "123456xxxxxx1234"
                    }
                ],
                "balances": [
                    {
                        "iban": "DE2310010010123456789"
                    }
                ],
                "transactions": [
                    {
                        "iban": "DE2310010010123456789"
                    },
                    {
                        "maskedPan": "123456xxxxxx1234"
                    }
                ]
            },
            "recurringIndicator": true
        }
    ]
}

I like (2) much better than (1) because (2) is a generic solution to convey information belonging to the consent given by the client and relevant for the client. Moreover, (1) is limited to the view of a certain access token whereas (2) effectively gives the information for the whole grant.

What do you think?

**Comment by jricher** [comment]
I'm more a fan of returning it with (2) but with the security and privacy considerations clearly spelled out that this must contain information relevant to the client, and that the RS will need its own mechanism for getting that info.

**Comment by b---c** [comment]
Also prefer (2) and agree w/ Justin on the considerations that it is information relevant to the client about the details of what authorization was given/granted.
