### ISSUE TITLE
Clarify semantics of common elements

### ISSUE THREAD

**Issue by tlodderstedt** [oauthstuff/draft-oauth-rar#55]
Basically, the type allows definition of use case/API specific schemas for authorization details. However, we have the common elements as well. How do those concepts interrelate? Does any authorization details type automatically include all of them? I think "datatypes" or "actions" might not be applicable in all cases. 

I suggest to differentiate between base elements that every authorization details type has and proposed elements, a certain authorization type definition might utilize, The first class consists of "type" and "locations" and is relevant for the basic processing rules for AS. The latter consists of "datatypes", "actions" and "identifiers".

Thoughts?

**Comment by jricher** [comment]
I mostly agree that these are of different classes. `type` is absolutely in its own category as it defines what the rest of the stack is about. I've separated it out from the rest in #52 as a start.

`locations` I'm less convinced by being separate, even though it has defined interactions with the `resource` parameter within RAR. 

The others are meant to be generally reusable, but we wouldn't expect every `type` to have them. There might be a handful of other general-purpose reusable fields with associated semantics as well, but I haven't seen much feedback as to what those would be yet. I based the `actions`, `locations`, and `datatypes` on what I've personally seen `scope`s used for in the wild, and the `identifier` comes from the use cases in healthcare (and later finance) that drove some of the parameterized-scope-value work in the past. Basically they should all be roughly orthogonal to each other, but ultimately `type` gets to decide which ones get used and which ones don't.

**Comment by tlodderstedt** [comment]
The interaction with `resource` to achieve per authorization details audience restriction is exactly what makes it tricky to leave 'locations' a common but optional field.

In my understanding, this means the designer of an authorization details elements type needs to add it to a particular "schema" definition in order to allow clients to allocate the authorization detail to a certain RS. That might work for specific deployments where the designer knows whether multiple RSs are present and relevant. I doubt this will work for use cases across deployments. If the designer forgets to include the 'locations' field multi RS deployments cannot utilize it. To me this is an indication that 'locations' needs special treatment. 

I suggest to define it as an optional but core element and leave it to the discretion of an AS to support it (with publication via metadata).

**Comment by steinarnoem** [comment]
Should/could the definitions, other than "type", be examples instead of specified type definitions?

**Comment by jricher** [comment]
@steinarnoem while it's technologically possible, I do think there's value in having a set of common-to-use dimensions. This will allow an API designer to start with something more than just a blank page, and hopefully, for example, lead to re-use across different APIs. The latter is important to developers who need to call multiple APIs and therefore need to structure their requests to fit each API. As such, I believe that having these common fields defined in the spec, and not having them just be used as examples, makes sense.
