### ISSUE TITLE
individual URI query parameters for multiple resource instances?

### ISSUE THREAD

**Issue by tlodderstedt** [oauthstuff/draft-oauth-rar#6]
Due to the change towards an array, we could also start by defining the atomic authorization_details/resource/resource_access object and only compose multiple instances if necessary. 

In case of a standard OAuth authorization request, a single object could be passed as parameter and multiple instances could be passed as multiple parameter instances. 

That would use the same pattern as resource indicators.

RAR combines resource indicators and scopes, so it might make sense to use the same pattern instead of having a top level array object in authorization requests 

In case of request objects and XYZ, a single object or an array could be used depending on the number of objects.

**Comment by tlodderstedt** [comment]
@jricher What do you think?

**Comment by jricher** [comment]
We could copy the pattern for consistency within OAuth 2. I don't particularly care for that pattern, but that's a personal programming preference. Besides, if we're doing JSON already, we might as well use JSON all the way through.

**Comment by tlodderstedt** [comment]
@b---c What do you think?

**Comment by b---c** [comment]
I agree with @jricher here that if we're doing JSON already, we might as well use JSON all the way through. Resource indicators used multiple parameter instances to allow for the value to be the URI and avoid inventing a list syntax of its own. But JSON has arrays/lists already.

**Comment by tlodderstedt** [comment]
what would be the top level JSON element in a URI? the array itself?

**Comment by jricher** [comment]
Yes, the top level would be a JSON array.

Also, RFC6749 already disallows repeated query parameter names, so I'm not sure how the resource identifier spec even gets around that. From §3.1:

> Request and response parameters MUST NOT be included more than once.

**Comment by tlodderstedt** [comment]
thanks. 

This means the example I included is correct. I'm fine with the outcome and will close this issue.

**Comment by b---c** [comment]
It could be done a number of different ways but that works.
