### ISSUE TITLE
Describe minimal AS product support level

### ISSUE THREAD

**Issue by tlodderstedt** [oauthstuff/draft-oauth-rar#63]
The question often arises what the AS products needs to do in order to support RAR. Most implementors are afraid of the expected complexity to support business logic on to0 of authorization details. 
I think the minimal level is:

- accept authorization_details parameter
- make authorization_details available to all endpoints
- allow custom logic to be implemented on top of authorization_details (user consent, transformation, augmentation, comparison)
- allow custom logic to pass modified authorization_details back to AS product
- support advertisement of supported authorization_details types in server metadata
- store consented authorization_details

**Comment by leastprivilege** [comment]
Maybe it would help to give some "user stories" or examples for 

> allow custom logic to be implemented on top of authorization_details (user consent, transformation, augmentation, comparison)

> allow custom logic to pass modified authorization_details back to AS product

To be able to come up with a design of the required extensibility points in the AS product.

Since you guys implemented already one or the other specialized scenario - it now up to "us" to generalize this.

**Comment by b---c** [comment]
While this is certainly useful information, it presumes a specific product and deployment architecture. It may well be a common one but is not exclusive. So something like this should be informational only and clearly qualified. Probably/maybe go in an appendix.

**Comment by leastprivilege** [comment]
Ah - yea - it wasn't my intention to put that into the RFC. It sounded like Torsten wanted to help implementers - that was my thought.

**Comment by tlodderstedt** [comment]
I was thinking about adding implementation considerations to the draft.

**Comment by vdzhuvinov** [comment]
I find this a good idea. To get implementers to think about the various aspects of RAR and not missing something crucial or something that may appear obvious to the authors.

I'm now studying the PR #64 and will post my comments there.

**Comment by tlodderstedt** [comment]
merged #64
