### ISSUE TITLE
Resource vs resource server

### ISSUE THREAD

**Issue by tlodderstedt** [oauthstuff/draft-oauth-rar#7]
What object does `locations` represent? Is it the (1) resource server or certain (2) resource(s)?

(1) in this case, we need a way to specify resources and actions on those resources in addition to `locations`
(2) We don't need the `identifier` in this case

**Comment by tlodderstedt** [comment]
@jricher 
I'm leaning towards making locations the resource URL. What's your opinion?

**Comment by jricher** [comment]
The intent with `locations` was a list of resource server URLs, with `identifier` being something more specific and abstract, like an account ID for a single-account access. For transactions that would need multiple parties, like a transfer of money, you'd probably not use `identifier` and instead use two values specific to the API. 

But ultimately, it's something that the RS and Client and AS can all agree is a requestable unit of the API, but bound to a physical URL of some kind.

**Comment by tlodderstedt** [comment]
We need to rework section "Relationship to "resource" parameter" based on the outcome of this discussion.
