### ISSUE TITLE
authorization_details still the best name?

### ISSUE THREAD

**Issue by tlodderstedt** [oauthstuff/draft-oauth-rar#8]
Given the latest changes, I think something like `resource_access` or `resource_scope` would be more appropriate.

**Comment by jricher** [comment]
I'd vote we keep `scope` out of the name due to overlap with the existing `scope` parameter. In XYZ so far it's called `resources`, but that's of course subject to change too.

**Comment by b---c** [comment]
+1 to keeping scope out of the name b/c of the existing scope parameter

**Comment by b---c** [comment]
resource_access seems ok. authorization_details is fine I think though. naming is hard

**Comment by tlodderstedt** [comment]
that train has left the station ...
