### ISSUE TITLE
URL-decoded value of remittanceInformationUnstructured

### ISSUE THREAD

**Issue by TakahikoKawasaki** [oauthstuff/draft-oauth-rar#98]
RAR draft 22 [Section 3](https://www.ietf.org/archive/id/draft-ietf-oauth-rar-22.html#section-3) says the URL-decoded value of `"remittanceInformationUnstructured"` is `"Ref Number Merchant"`.

(From "[Figure 9](https://www.ietf.org/archive/id/draft-ietf-oauth-rar-22.html#figure-9): [URL decoded authorization_details.](https://www.ietf.org/archive/id/draft-ietf-oauth-rar-22.html#name-url-decoded-authorization_d)")
```json
"remittanceInformationUnstructured": "Ref Number Merchant"
```

However, the exact value should be `"RefNumberMerchant"`. Either the decoded value or the original encoded value needs to be corrected.

**Comment by bc-pi** [comment]
thanks Taka
