### ISSUE TITLE
question: authorization_details in id-token?

### ISSUE THREAD

**Issue by joostreuzel** [oauthstuff/draft-oauth-rar#99]
Hi,

Thanks for this specification. It allows for incredible rich descriptions of authorization rules.

One question I have is how this would relate to OIDC id-tokens. Would it be opportune to add authorization_details to the id-token? For example, if the user is provided access to certain data types and permissions on the application, would it make sense to add these to the id-token? Or would the id-token just hold authentication information and no authorization information?

Regards,
Joost

**Comment by joostreuzel** [comment]
That is an interesting restriction of the purpose of `authorization_details`. 

The use case I am working on is about delegated administration, where the RP delegates user authentication and most of its authorization logic to the AS. The AS not only authenticates the user, but -- based on customer set policies -- also indicates what permissions the user has on the RP itself. For example which to which tenant and in which role the user has access at the RP. What we miss in OIDC is a standard to communicate such authorization rules to the RP. We thought that RAR may be that standard.

In this model, `authorization_details` would be used beyond indicating what the access token can do. It would be used together with the ID token to tell the RP who the user is, and what that user is allowed to do at the RP.

**Comment by steinarnoem** [comment]
The way I perceive authorization_details is as an extension of the "scope" parameter in OAuth; basically a way to adding more detail about what the user gives his consent to when the client requests access to a RS. The contents of the details-structure is useful for doing access control, accountability (traceability, logging etc) at the RS. In other words not a part of the OIDC flow.

But, I guess an Access Token that is issued to the RP/Client for accessing the OP could contain an "authorization_details" structure - not sure if that is relevant for your case.
 
Have you considered the "claims" parameter in OIDC? It sounds like that might be closer to your expectations?
https://openid.net/specs/openid-connect-core-1_0.html#ClaimsParameter

**Comment by joostreuzel** [comment]
The claims parameter may indeed be what I was looking for. We can add a custom claim with role/tenant information there, splitting RP and AT level permissions over custom OIDC claims and authorization_details.

Perhaps it is worthwhile to add a minor clarifying note on this somewhere in the RAR specification?

Thank you.
